stages:
  - build

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - TAG=$CI_COMMIT_SHA
    - if [ -n "$CI_COMMIT_TAG" ]; then TAG=$CI_COMMIT_TAG; fi
    - docker build -t $CI_REGISTRY_IMAGE:$TAG .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$TAG
    - docker rmi $CI_REGISTRY_IMAGE:$TAG
  allow_failure: true
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - when: manual