version: '3'

services:
  app:
    image: registry.csc.sibsutis.ru/iv923s21/virtualization:01ae224e36d0bbf35d56563134482b6551989cf5
    ports:
      - "8080:80"
    networks:
      - web

  whoami:
    image: traefik/whoami
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.example.com`)"
      - "traefik.http.routers.whoami.entrypoints=web"
    networks:
      - web

  proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
      - whoami
    networks:
      - web

networks:
  web:
    driver: bridge